version: '3.9'
services:
  postgres:
    container_name: postgres_int_emp_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ifpb
      PGDATA: /data/postgres
    volumes:
      - postgres-data:/data/postgres
    ports:
      - "6000:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_int_emp_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ifpb@ifpb.edu.br
      PGADMIN_DEFAULT_PASSWORD: ifpb
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    depends_on:
      - postgres
    restart: unless-stopped

networks:
  postgres:

volumes:
  postgres-data:
  pgadmin-data: