version: '3.9'
services:
  # docker build -t <image-name:tag-name> . --build-arg FILE=<backup-file-name> --build-arg DBNAME=<database-name>
  postgres:
    container_name: postgres_int_emp_container
    build:
      context: .
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ifpb
      PGDATA: /data/postgres

      # Restore
      PATH_RESTORE_FILE: /common/
      RESTORE_FILE: northwind_erp.backup
      # DLL
      PATH_DLL_FILE: /northwind/app/
      DLL_FILE: create_northwind_script.sql

    volumes:
      - postgres-int-emp-data:/data/postgres
    ports:
      - "6000:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_int_emp_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ifpb@ifpb.edu.br
      PGADMIN_DEFAULT_PASSWORD: ifpb
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin-int-emp-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    depends_on:
      - postgres
    restart: unless-stopped

networks:
  postgres:

volumes:
  postgres-int-emp-data:
  pgadmin-int-emp-data: